### ISSUE TITLE
Create a Customer Account

### ISSUE THREAD

**Issue by jmyanish** [devops-customers/customers#1]
As a customer
I need to be able to create a customer profile
So that my data can be saved for future reference
   
 ### Details and Assumptions
 * will need customer first and last name
 * will need customer ID (unique)
 * will need userid and passworld
 * will need address (at least one, option for more)
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a customer enters the ecommerce site
 When they click 'create an account'
 Then there is a form with the applicable fields that will save their information into a database
 ```

**Comment by jm9498** [comment]
- Customers have at least one address. You will need to implement a subordinate 
REST API to store one or more addresses (e.g., /customers/{id}/addresses)
