### ISSUE TITLE
Query Resources by some attribute of the Resource (List Customer BY email)

### ISSUE THREAD

**Issue by winnywunyu** [devops-customers/customers#13]
**As a** BA
 **I need** to able to search customers by email address
 **So that** the information can be pulled out to make further analysis or updates
   
 ### Details and Assumptions
 * add this functionality to the ROUTES file. Not that we already have some of this functionality, so just add the others (phone number, etc)
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that a BA needs to find a customer
 When BA searches by email address
 Then the customer is found and returned
 ```

**Comment by jmyanish** [comment]
assuming technical debt bc a customer wouldn't list all accounts

**Comment by jm9498** [comment]
Just thinking - would it make more sense to query by customer ID or email vs. address? (I guess if I was a customer support agent I'd search by address, email, or customer ID - just wonder if there could be issues where you have more than 1 customer in a single address for example)

**Comment by jmyanish** [comment]
Totally agree, great point! I've updated the issue.
