### ISSUE TITLE
Suspend a customer account

### ISSUE THREAD

**Issue by winnywunyu** [devops-customers/customers#34]
**As a** BA
 **I need** to suspend a customer account
 **So that** we can avoid situations such as bot customer, fake account, invalid payment...etc
   
 ### Details and Assumptions
 * Suspend a customer account
 ### Acceptance Criteria  
   
 ```gherkin
 Given that there might be fraud activities
 When an account is identified as fake 
 Then we can suspend the account
 ```

**Comment by jmyanish** [comment]
add flag to the customer model and then toggle that flag when the endpoint is called.
