### ISSUE TITLE
Create database model and schema

### ISSUE THREAD

**Issue by zedfan123456** [devops-customers/customers#4]
**As a** developer 
 **I need** a database for customers  
 **So that** customers' infomation can be stored  
   
 ### Details and Assumptions
 *  At a minimum it should have the customer’s first and last name along with some customer id that 
can be used as a key for uniquely identifying them. It may even have a userid and password. It’s 
up to you. Customers also have at least one address.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a database is created
 When a customer is created
 Then we can list the customers
 ```

**Comment by jm9498** [comment]
- Create database model and schema
