### ISSUE TITLE
List all Customer Accounts

### ISSUE THREAD

**Issue by jm9498** [devops-customers/customers#8]
**As a** company employee
 **I need** to pull a list of all customer accounts
 **So that** I can check for errors
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I need to check from customer input errors
 When I pull a list of customers
 Then a list of customers is displayed with all of their details
 ```

**Comment by jmyanish** [comment]
assuming technical debt bc a customer wouldn't list all accounts
